# Generated by Django 5.1 on 2024-09-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/course_image/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
