# Generated by Django 5.1 on 2024-09-17 10:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesManagement', '0002_alter_course_course_image_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_modules',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='registered_student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Add about course'),
        ),
    ]
